awsAccount: hnd
k8sPrefix: awsd
customer: hydra
purpose: dataplatform
stage: dev

replicaCount: 3

image:
  repository: dcoppa/saml-proxy
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: "samlproxy"
fullnameOverride: "samlproxy"

podAnnotations: {}

podSecurityContext:
  fsGroup: 0

securityContext:
  capabilities:
    add:
    - NET_BIND_SERVICE
    drop:
    - all
  runAsNonRoot: true
  runAsUser: 33

service:
  type: ClusterIP
  port: 32766
  containerPort: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            "app.kubernetes.io/name": "samlproxy"
            "app.kubernetes.io/instance": "samlproxy"
        topologyKey: "topology.kubernetes.io/zone"

proxy:
  backend: https://awsd-svc-hydra-dataplatform-traefik-admin-dev.awsd-ns-hydra-dataplatform-traefik-admin-dev.svc
  hostname: k8s.example.com
  nlbhostname: xxxxxxxxxxxxxxxx.elb.eu-west-1.amazonaws.com
