{{- if and .Values.certController.create .Values.certController.metrics.service.enabled (not .Values.webhook.certManager.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-{{ include "external-secrets.fullname" . }}-cc-m-{{.Values.stage}}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.certController.metrics.service.port }}
    protocol: TCP
    targetPort: metrics
    name: metrics
  selector:
    {{- include "external-secrets-cert-controller.selectorLabels" . | nindent 4 }}
{{- end }}
