{{- if .Values.metrics.prometheus }}
{{- if .Values.metrics.prometheus.service }}
{{- if (.Values.metrics.prometheus.service).enabled -}}

{{- $fullname := (printf "%s-svc-%s-%s-%s-m-%s" .Values.k8sPrefix .Values.customer .Values.purpose (include "traefik.fullname" .) .Values.stage) }}
{{- if ge (len $fullname) 50 }}
  {{- fail "ERROR: Cannot create a metrics service when name contains more than 50 characters" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc-%s-%s-%s-%s" .Values.k8sPrefix .Values.customer .Values.purpose (include "traefik.service-name" (dict "root" . "name" "m")) .Values.stage }}
  namespace: {{ template "traefik.namespace" . }}
  {{- template "traefik.metrics-service-metadata" . }}
  annotations:
  {{- with .Values.metrics.prometheus.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "traefik.labelselector" . | nindent 4 }}
  ports:
  - port: {{ .Values.ports.metrics.port }}
    name: "metrics"
    targetPort: metrics
    protocol: TCP
    {{- if .Values.ports.metrics.nodePort }}
    nodePort: {{ .Values.ports.metrics.nodePort }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
