apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.k8sPrefix}}-sa-{{.Values.customer}}-{{.Values.purpose}}-tigera-operator-{{.Values.stage}}
  namespace: {{.Release.Namespace}}
imagePullSecrets: {{- include "tigera-operator.imagePullSecrets" . | nindent 2 }}
