{{- if not .Values.metrics.disableAuth }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-clusterrole-{{.Values.customer}}-{{.Values.purpose}}-{{ include "snapscheduler.fullname" . }}-m-{{.Values.stage}}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
