{{- if not .Values.metrics.disableAuth }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "snapscheduler.fullname" . }}-proxy
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "snapscheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "snapscheduler.fullname" . }}-proxy
  apiGroup: rbac.authorization.k8s.io
{{- end }}
