apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-rolebinding-{{.Values.customer}}-{{.Values.purpose}}-{{ include "snapscheduler.fullname" . }}-le-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Values.k8sPrefix}}-role-{{.Values.customer}}-{{.Values.purpose}}-{{ include "snapscheduler.fullname" . }}-le-{{.Values.stage}}
subjects:
- kind: ServiceAccount
  name: {{ include "snapscheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
