{{- if not .Values.metrics.disableAuth }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-clusterrolebinding-{{.Values.customer}}-{{.Values.purpose}}-{{ include "snapscheduler.fullname" . }}-proxy-{{.Values.stage}}
subjects:
- kind: ServiceAccount
  name: {{ include "snapscheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{.Values.k8sPrefix}}-clusterrole-{{.Values.customer}}-{{.Values.purpose}}-{{ include "snapscheduler.fullname" . }}-proxy-{{.Values.stage}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
