{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snapscheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
{{- end -}}
