apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapscheduler.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "snapscheduler.selectorLabels" . | nindent 4 }}
