apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-{{ include "snapscheduler.fullname" . }}-m-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "snapscheduler.selectorLabels" . | nindent 4 }}
