apiVersion: v1
kind: Service
metadata:
  labels: {{ include "traefik.labels" . | nindent 4 }}
    k8s-app: nginx-fallback
  name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-nginx-fallback-{{.Values.stage}}
  namespace: {{ template "traefik.namespace" . }}
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector: {{ include "traefik.labelselector" . | nindent 4 }}
    k8s-app: nginx-fallback
  type: ClusterIP
