apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
    k8s-app: nginx-fallback
  name: {{.Values.k8sPrefix}}-cm-{{.Values.customer}}-{{.Values.purpose}}-nginx-fallback-html-{{.Values.stage}}
  namespace: {{ template "traefik.namespace" . }}
data:
  healthcheck.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Healthckeck</title></head>
    <body>OK</body>
    </html>
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>INDEX</title></head>
    <body>OK</body>
    </html>
