{{- range $name, $config := .Values.tlsStore }}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  labels:
    {{- include "traefik.labels" $ | nindent 4 }}
    traffic-type: admin
  name: {{ $name }}
  namespace: {{ template "traefik.namespace" $ }}
spec:
  {{- toYaml $config | nindent 2 }}
---
{{- end -}}
