{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "newrelic-logging.labels" . | indent 4 }}
  name: {{.Values.k8sPrefix}}-clusterrole-{{.Values.customer}}-{{.Values.purpose}}-{{ template "newrelic-logging.fullname" . }}-{{.Values.stage}}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
{{- if .Values.rbac.pspEnabled }}
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{.Values.k8sPrefix}}-psp-{{.Values.customer}}-{{.Values.purpose}}-{{ template "newrelic-logging.fullname" . }}-{{.Values.stage}}
    verbs:
      - use
{{- end -}}
{{- end -}}
