apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{.Values.k8sPrefix}}-es-{{.Values.customer}}-{{.Values.purpose}}-{{ include "newrelic-logging.fullname" . }}-license-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic-logging.labels" . | indent 4 }}
spec:
  data:
  - remoteRef:
      key: {{.Values.awsAccount}}-secret-{{.Values.customer}}-{{.Values.purpose}}-nr-licensekey-{{.Values.stage}}
      property: {{ include "newrelic-logging.customSecretKey" . }}
    secretKey: key
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{.Values.k8sPrefix}}-css-{{.Values.customer}}-{{.Values.purpose}}-aws-secretsmanager-{{.Values.stage}}
  target:
    creationPolicy: Owner
    name: {{ include "newrelic-logging.customSecretName" . }}
    template:
      data:
        {{ include "newrelic-logging.customSecretKey" . }}: {{ (printf "\"{{ .key }}\"") }}
      metadata:
        labels:
          {{- include "newrelic-logging.labels" . | indent 10 }}
      engineVersion: v2
      type: Opaque
