{{- if .Values.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{.Values.k8sPrefix}}-psp-{{.Values.customer}}-{{.Values.purpose}}-{{ template "newrelic-logging.fullname" . }}-{{.Values.stage}}
spec:
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  hostPID: true
  hostIPC: true
  hostPorts:
  - min: 1
    max: 65536
{{- end }}
