kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.k8sPrefix}}-clusterrolebinding-{{.Values.customer}}-{{.Values.purpose}}-tigera-operator-{{.Values.stage}}
subjects:
- kind: ServiceAccount
  name: {{.Values.k8sPrefix}}-sa-{{.Values.customer}}-{{.Values.purpose}}-tigera-operator-{{.Values.stage}}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Values.k8sPrefix}}-clusterrole-{{.Values.customer}}-{{.Values.purpose}}-tigera-operator-{{.Values.stage}}
  apiGroup: rbac.authorization.k8s.io
