{{- if .Values.webhook.enabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret-%s-%s-%s-cert-%s" .Values.k8sPrefix .Values.customer .Values.purpose (include "karpenter.fullname" .) .Values.stage) -}}
{{- if not $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.k8sPrefix}}-secret-{{.Values.customer}}-{{.Values.purpose}}-{{ include "karpenter.fullname" . }}-cert-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# data: {} # Injected by karpenter-webhook
{{- end -}}
{{- end }}
