apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{.Values.k8sPrefix}}-clusterpolicy-{{.Values.customer}}-{{.Values.purpose}}-pod-antiaffinity-sts-{{.Values.stage}}
  annotations:
    policies.kyverno.io/title: Add Pod Anti-Affinity
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/subject: StatefulSet, Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Applications may involve multiple replicas of the same Pod for
      availability as well as scale purposes, yet Kubernetes does not by default
      provide a solution for availability. This policy sets a Pod anti-affinity
      configuration on StatefulSets which contain an `app.kubernetes.io/name`
      label if it is not already present.
spec:
  rules:
    - name: insert-pod-antiaffinity-statefulset
      match:
        any:
        - resources:
            kinds:
              - StatefulSet
      preconditions:
        all:
        - key: {{`"{{request.object.spec.template.metadata.labels.\"app.kubernetes.io/name\" || ''}}"`}}
          operator: NotEquals
          value: ""
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                +(affinity):
                  +(podAntiAffinity):
                    +(preferredDuringSchedulingIgnoredDuringExecution):
                      - weight: 100
                        podAffinityTerm:
                          topologyKey: "topology.kubernetes.io/zone"
                          labelSelector:
                            matchExpressions:
                            - key: app.kubernetes.io/name
                              operator: In
                              values:
                              - {{`"{{request.object.spec.template.metadata.labels.\"app.kubernetes.io/name\"}}"`}}
