{{- if .Values.secretConfiguration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.k8sPrefix}}-secret-{{.Values.customer}}-{{.Values.purpose}}-{{ include "external-dns.fullname" . }}-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretConfiguration.data }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end }}
