{{- if .Values.cluster.create }}
---
apiVersion: kaap.oss.datastax.com/v1beta1
kind: PulsarCluster
metadata:
  name: {{ .Values.cluster.spec.global.name | quote }}
spec:
  {{- toYaml .Values.cluster.spec | nindent 2 }}
{{- end }}
