{{- if and .Values.cluster.create .Values.pulsarAdminConsole.create }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  labels:
    {{- include "kaap.labels" . | nindent 4 }}
    component: adminconsole
    cluster: {{ .Values.cluster.spec.global.name }}
    traffic-type: admin
  name: {{.Values.k8sPrefix}}-serverstransport-{{.Values.customer}}-{{.Values.purpose}}-{{ .Values.cluster.spec.global.name }}-console-{{.Values.stage}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  insecureSkipVerify: true
{{- end }}
