{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kaap.labels" . | nindent 4 }}
  name: {{ include "kaap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
