{{- if .Values.cainjector.enabled }}
{{- if .Values.global.podSecurityPolicy.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.k8sPrefix}}-clusterrole-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-cainj-psp-{{.Values.stage}}
  labels:
    app: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "cainjector"
    {{- include "labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{.Values.k8sPrefix}}-psp-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-cainj-{{.Values.stage}}
{{- end }}
{{- end }}
