{{- if .Values.cainjector.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.Values.k8sPrefix}}-pdb-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-cainj-{{.Values.stage}}
  namespace: {{ include "cert-manager.namespace" . }}
  labels:
    app: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "cainjector"
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: "cainjector"

  {{- if not (or (hasKey .Values.cainjector.podDisruptionBudget "minAvailable") (hasKey .Values.cainjector.podDisruptionBudget "maxUnavailable")) }}
  minAvailable: 1 # Default value because minAvailable and maxUnavailable are not set
  {{- end }}
  {{- if hasKey .Values.cainjector.podDisruptionBudget "minAvailable" }}
  minAvailable: {{ .Values.cainjector.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.cainjector.podDisruptionBudget "maxUnavailable" }}
  maxUnavailable: {{ .Values.cainjector.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
