{{- if .Values.cainjector.config -}}
{{- $_ := .Values.cainjector.config.apiVersion | required ".Values.cainjector.config.apiVersion must be set !" -}}
{{- $_ := .Values.cainjector.config.kind | required ".Values.cainjector.config.kind must be set !" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.k8sPrefix}}-cm-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-cainj-{{.Values.stage}}
  namespace: {{ include "cert-manager.namespace" . }}
  labels:
    app: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "cainjector.name" . }}
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "cainjector"
    {{- include "labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.cainjector.config | toYaml | nindent 4 }}
{{- end -}}
