{{- if .Values.webhook.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Values.k8sPrefix}}-networkpolicy-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-wh-allow-egress-{{.Values.stage}}
  namespace: {{ include "cert-manager.namespace" . }}
spec:
  egress:
    {{- with .Values.webhook.networkPolicy.egress }}
      {{- toYaml . | nindent 2 }}
    {{- end }}
  podSelector:
    matchLabels:
      app: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
      app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: "webhook"
      {{- with .Values.webhook.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  policyTypes:
  - Egress
{{- end }}
