{{- if .Values.global.podSecurityPolicy.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{.Values.k8sPrefix}}-psp-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-wh-{{.Values.stage}}
  labels:
    app: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
    {{- include "labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    {{- if .Values.global.podSecurityPolicy.useAppArmor }}
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
    {{- end }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities: []  # default set of capabilities are implicitly allowed
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  hostNetwork: {{ .Values.webhook.hostNetwork }}
  {{- if .Values.webhook.hostNetwork }}
  hostPorts:
  - max: {{ .Values.webhook.securePort }}
    min: {{ .Values.webhook.securePort }}
  {{- end }}
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 1000
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 1000
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 1000
{{- end }}
