{{- if .Values.global.podSecurityPolicy.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.k8sPrefix}}-clusterrole-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-wh-psp-{{.Values.stage}}
  labels:
    app: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
    {{- include "labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{.Values.k8sPrefix}}-psp-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-wh-{{.Values.stage}}
{{- end }}
