apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cert-manager-mutating-webhook-cfg
  labels:
    app: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}-{{ include "webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "webhook"
    {{- include "labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from-secret: {{ printf "%s/%s-secret-%s-%s-cert-manager-wh-ca-%s" (include "cert-manager.namespace" .) .Values.k8sPrefix .Values.customer .Values.purpose .Values.stage | quote }}
    {{- with .Values.webhook.mutatingWebhookConfigurationAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
webhooks:
  - name: webhook.cert-manager.io
    {{- with .Values.webhook.mutatingWebhookConfiguration.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    rules:
      - apiGroups:
          - "cert-manager.io"
        apiVersions:
          - "v1"
        operations:
          - CREATE
        resources:
          - "certificaterequests"
    admissionReviewVersions: ["v1"]
    # This webhook only accepts v1 cert-manager resources.
    # Equivalent matchPolicy ensures that non-v1 resource requests are sent to
    # this webhook (after the resources have been converted to v1).
    matchPolicy: Equivalent
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    failurePolicy: Fail
    # Only include 'sideEffects' field in Kubernetes 1.12+
    sideEffects: None
    clientConfig:
      {{- if .Values.webhook.url.host }}
      url: https://{{ .Values.webhook.url.host }}/mutate
      {{- else }}
      service:
        name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-cert-manager-wh-{{.Values.stage}}
        namespace: {{ include "cert-manager.namespace" . }}
        path: /mutate
      {{- end }}
