# -- Internal settings used with `helm template` to generate install manifest
# @ignored
templating:
  enabled: false
  debug: false
  version: ~

groups:

  # -- Install CRDs in group `kyverno.io`
  kyverno:
    admissionreports: true
    backgroundscanreports: true
    cleanuppolicies: true
    clusteradmissionreports: true
    clusterbackgroundscanreports: true
    clustercleanuppolicies: true
    clusterpolicies: true
    globalcontextentries: true
    policies: true
    policyexceptions: true
    updaterequests: true

  # -- Install CRDs in group `reports.kyverno.io`
  reports:
    clusterephemeralreports: true
    ephemeralreports: true

  # -- Install CRDs in group `wgpolicyk8s.io`
  wgpolicyk8s:
    clusterpolicyreports: true
    policyreports: true

# -- Additional CRDs annotations
annotations: {}
  # argocd.argoproj.io/sync-options: Replace=true
  # strategy.spinnaker.io/replace: 'true'

# -- Additional CRDs labels
customLabels: {}
