annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add profiling support
    - kind: added
      description: Add global nodeSelector
    - kind: added
      description: Add podLabels to the post-upgrade hook
    - kind: added
      description: Add podLabels to the pre-delete hook
  artifacthub.io/links: |
    - name: Documentation
      url: https://kyverno.io/docs
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: v1.12.0-rc.3
dependencies:
- condition: crds.install
  name: crds
  repository: ""
  version: 3.2.0-rc.3
description: Kubernetes Native Policy Management
home: https://kyverno.io/
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- policy agent
- policy
- validating webhook
- admission controller
- mutation
- mutate
- validate
- generate
- supply chain
- security
kubeVersion: '>=1.25.0-0'
maintainers:
- name: Nirmata
  url: https://kyverno.io/
name: kyverno
sources:
- https://github.com/kyverno/kyverno
type: application
version: 3.2.0-rc.3
