{{- if .Values.nsqadmin.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.k8sPrefix}}-ing-{{.Values.customer}}-{{.Values.purpose}}-{{ include "nsq.nsqadmin.fullname" . }}-{{.Values.stage}}
  labels:
    {{- include "nsq.commonLabels" . | nindent 4 }}
  {{- with .Values.nsqadmin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nsqadmin.ingress.ingressClassName }}
  ingressClassName: {{ .Values.nsqadmin.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.nsqadmin.ingress.tls }}
  tls:
    {{- range .Values.nsqadmin.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-{{ include "nsq.nsqadmin.fullname" . }}-{{.Values.stage}}
            port:
              number: {{ .Values.nsqadmin.service.port }}
    {{- if .Values.nsqadmin.ingress.host }}
    host: {{ .Values.nsqadmin.ingress.host | quote }}
    {{- end }}
{{- end }}
