apiVersion: v1
kind: Service
metadata:
  name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-{{ include "nsq.nsqlookupd.fullname" . }}-{{.Values.stage}}
  labels:
    {{- include "nsq.commonLabels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 4160
    name: tcp
    targetPort: 4160
  - port: 4161
    name: http
    targetPort: 4161
  selector:
    {{- include "nsq.nsqlookupd.selectorLabels" . | nindent 4 }}
