{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.k8sPrefix}}-svc-{{.Values.customer}}-{{.Values.purpose}}-{{ template "nifikop.fullname" . }}-m-{{.Values.stage}}
  namespace: {{ $.Release.Namespace }}
  labels:
    component: app
    app: {{ template "nifikop.name" . }}-metrics
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "userdefined.labels" . }}
  annotations:
    {{- include "userdefined.annotations" . }}
spec:
  selector:
    app: {{ template "nifikop.name" . }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
{{- end }}
