apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    {{- include "samlproxy.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-cm-{{.Values.customer}}-{{.Values.purpose}}-{{ include "samlproxy.fullname" . }}-html-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
data:
  healthcheck.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Healthckeck</title></head>
    <body>OK</body>
    </html>
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>INDEX</title></head>
    <body>OK</body>
    </html>
