apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "samlproxy.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-cm-{{.Values.customer}}-{{.Values.purpose}}-{{ include "samlproxy.fullname" . }}-idp-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
data:
  saml_idp.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <EntityDescriptor ID="_aafe8592-1813-4614-b23e-940b9e3b437c"
        entityID="https://sts.windows.net/56564e0f-83d3-4b52-92e8-a6bb9ea36564/"
        xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
        <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <Reference URI="#_aafe8592-1813-4614-b23e-940b9e3b437c">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <DigestValue>KfV080uz9b0nBi6Y3cXxkHyu/XIK3+QsguirZtpHI5E=</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>
                hx/cZ/T6JRdK5j88S2hQKzSkiigejNC8f1pLtQvIVnR0TQX3eyW0oxjiDGWAZb+o2RLbR/k7/MwY8qaidOCrY30yFrWFo+7fXxUC/+iyYzfT85mml8azIAb8uZh9BcE0ZfEpGVaiWeVDvVSDsGkFAK3dgiCgJySZ71OJH/mHmnwIug10HRno9hi3KbIpH4LQQlWrVLFgNgmfXA+IzWJ1NnnchpC5cTPCeKKh7uXPA6EksEuiHP+ZacNutDa8mtjIPl9k038wbnW9OV9Y2xIyMKmrdY870i8gbPbG1q8TQFBU9eyjNNamEfMGg8CWIlAt04pYj9dFRiMkWRqP0cxkVw==</SignatureValue>
            <KeyInfo>
                <X509Data>
                    <X509Certificate>
                        MIIC8DCCAdigAwIBAgIQHyn3TUD73aRKdHUKO4eofzANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMzA4MTYxMjAxNTFaFw0yNjA4MTYxMjAxNTBaMDQxMjAwBgNVBAMTKU1pY3Jvc29mdCBBenVyZSBGZWRlcmF0ZWQgU1NPIENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3moERWAUAXad8gE+6k+I0oqjEeB281VDzPWc4ISAqHcXsPrxKO3JTKg/EhLO+zeJTC4J9gZu0tvonYcQ8nk55t9WvkZvj6omvS30GnPZ4lMTXWxadhNCouvZbve24ntWRkbWEXpQj7wRQ2uLPSgYDxoDkT4Jujt7QEZLO8zFpBhZrX4Yi4COFcCySFkzMTzjfDRwJ94+b+OMZuI7qo2XjGfrvdY4Z75Jd96dBq92H9f8UVTHBJW4Ked9hBt1T33/goW9lekMlZ0eB78Rlq7KD+jiKJA1BqYBtyZWgE2b96Nr+By0lwQeqL2rz2DB1c6NVaLinjhsUTttc6NzVeHV5QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCvrt8pxS8FQubZfSGQ4m4g8EkgRHMM84DdyGyATOoCpQG5m09Q9xDmOupcb14fnDD3ScRLRAZCkOEgC3rYi8EgzQ+9KtTBLYNY2zHGW9QKDQWyKinXs+BsUTFQI02y1qM2A+0iy9O1CW1/iYu/q36OuxE9+Lj4bZfTU1KGL7e/fsrQfI82nZ9qeix0YGItgvOwK7QPqTanLdteImv8/IQMm6jZz8wvY3dEfilFPHMnfWznU8fucEWejtPKIuL1h600hNWubtbpgKFAGCauGP1x/2252zIT2vnces5nDzTAZX9cP5UTifPyQhC4i/YkWdN9IaKU/GYouU9AHVsYMraJ</X509Certificate>
                </X509Data>
            </KeyInfo>
        </Signature>
        <RoleDescriptor xsi:type="fed:SecurityTokenServiceType"
            protocolSupportEnumeration="http://docs.oasis-open.org/wsfed/federation/200706"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:fed="http://docs.oasis-open.org/wsfed/federation/200706">
            <KeyDescriptor use="signing">
                <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                    <X509Data>
                        <X509Certificate>
                            MIIC8DCCAdigAwIBAgIQHyn3TUD73aRKdHUKO4eofzANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMzA4MTYxMjAxNTFaFw0yNjA4MTYxMjAxNTBaMDQxMjAwBgNVBAMTKU1pY3Jvc29mdCBBenVyZSBGZWRlcmF0ZWQgU1NPIENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3moERWAUAXad8gE+6k+I0oqjEeB281VDzPWc4ISAqHcXsPrxKO3JTKg/EhLO+zeJTC4J9gZu0tvonYcQ8nk55t9WvkZvj6omvS30GnPZ4lMTXWxadhNCouvZbve24ntWRkbWEXpQj7wRQ2uLPSgYDxoDkT4Jujt7QEZLO8zFpBhZrX4Yi4COFcCySFkzMTzjfDRwJ94+b+OMZuI7qo2XjGfrvdY4Z75Jd96dBq92H9f8UVTHBJW4Ked9hBt1T33/goW9lekMlZ0eB78Rlq7KD+jiKJA1BqYBtyZWgE2b96Nr+By0lwQeqL2rz2DB1c6NVaLinjhsUTttc6NzVeHV5QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCvrt8pxS8FQubZfSGQ4m4g8EkgRHMM84DdyGyATOoCpQG5m09Q9xDmOupcb14fnDD3ScRLRAZCkOEgC3rYi8EgzQ+9KtTBLYNY2zHGW9QKDQWyKinXs+BsUTFQI02y1qM2A+0iy9O1CW1/iYu/q36OuxE9+Lj4bZfTU1KGL7e/fsrQfI82nZ9qeix0YGItgvOwK7QPqTanLdteImv8/IQMm6jZz8wvY3dEfilFPHMnfWznU8fucEWejtPKIuL1h600hNWubtbpgKFAGCauGP1x/2252zIT2vnces5nDzTAZX9cP5UTifPyQhC4i/YkWdN9IaKU/GYouU9AHVsYMraJ</X509Certificate>
                    </X509Data>
                </KeyInfo>
            </KeyDescriptor>
            <fed:ClaimTypesOffered>
                <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Name</auth:DisplayName>
                    <auth:Description>The mutable display name of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType
                    Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Subject</auth:DisplayName>
                    <auth:Description>An immutable, globally unique, non-reusable identifier of the user
                        that is unique to the application for which a token is issued.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Given Name</auth:DisplayName>
                    <auth:Description>First name of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Surname</auth:DisplayName>
                    <auth:Description>Last name of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/displayname"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Display Name</auth:DisplayName>
                    <auth:Description>Display name of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/nickname"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Nick Name</auth:DisplayName>
                    <auth:Description>Nick name of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType
                    Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Authentication Instant</auth:DisplayName>
                    <auth:Description>The time (UTC) when the user is authenticated to Windows Azure
                        Active Directory.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType
                    Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Authentication Method</auth:DisplayName>
                    <auth:Description>The method that Windows Azure Active Directory uses to
                        authenticate users.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/objectidentifier"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>ObjectIdentifier</auth:DisplayName>
                    <auth:Description>Primary identifier for the user in the directory. Immutable,
                        globally unique, non-reusable.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/tenantid"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>TenantId</auth:DisplayName>
                    <auth:Description>Identifier for the user's tenant.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/identityprovider"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>IdentityProvider</auth:DisplayName>
                    <auth:Description>Identity provider for the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Email</auth:DisplayName>
                    <auth:Description>Email address of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Groups</auth:DisplayName>
                    <auth:Description>Groups of the user.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/accesstoken"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>External Access Token</auth:DisplayName>
                    <auth:Description>Access token issued by external identity provider.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/expiration"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>External Access Token Expiration</auth:DisplayName>
                    <auth:Description>UTC expiration time of access token issued by external identity
                        provider.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/openid2_id"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>External OpenID 2.0 Identifier</auth:DisplayName>
                    <auth:Description>OpenID 2.0 identifier issued by external identity provider.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/claims/groups.link"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>GroupsOverageClaim</auth:DisplayName>
                    <auth:Description>Issued when number of user's group claims exceeds return limit.</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>Role Claim</auth:DisplayName>
                    <auth:Description>Roles that the user or Service Principal is attached to</auth:Description>
                </auth:ClaimType>
                <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/wids"
                    xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                    <auth:DisplayName>RoleTemplate Id Claim</auth:DisplayName>
                    <auth:Description>Role template id of the Built-in Directory Roles that the user is
                        a member of</auth:Description>
                </auth:ClaimType>
            </fed:ClaimTypesOffered>
            <fed:SecurityTokenServiceEndpoint>
                <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                    <wsa:Address>
                        https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/wsfed</wsa:Address>
                </wsa:EndpointReference>
            </fed:SecurityTokenServiceEndpoint>
            <fed:PassiveRequestorEndpoint>
                <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                    <wsa:Address>
                        https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/wsfed</wsa:Address>
                </wsa:EndpointReference>
            </fed:PassiveRequestorEndpoint>
        </RoleDescriptor>
        <RoleDescriptor xsi:type="fed:ApplicationServiceType"
            protocolSupportEnumeration="http://docs.oasis-open.org/wsfed/federation/200706"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:fed="http://docs.oasis-open.org/wsfed/federation/200706">
            <KeyDescriptor use="signing">
                <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                    <X509Data>
                        <X509Certificate>
                            MIIC8DCCAdigAwIBAgIQHyn3TUD73aRKdHUKO4eofzANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMzA4MTYxMjAxNTFaFw0yNjA4MTYxMjAxNTBaMDQxMjAwBgNVBAMTKU1pY3Jvc29mdCBBenVyZSBGZWRlcmF0ZWQgU1NPIENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3moERWAUAXad8gE+6k+I0oqjEeB281VDzPWc4ISAqHcXsPrxKO3JTKg/EhLO+zeJTC4J9gZu0tvonYcQ8nk55t9WvkZvj6omvS30GnPZ4lMTXWxadhNCouvZbve24ntWRkbWEXpQj7wRQ2uLPSgYDxoDkT4Jujt7QEZLO8zFpBhZrX4Yi4COFcCySFkzMTzjfDRwJ94+b+OMZuI7qo2XjGfrvdY4Z75Jd96dBq92H9f8UVTHBJW4Ked9hBt1T33/goW9lekMlZ0eB78Rlq7KD+jiKJA1BqYBtyZWgE2b96Nr+By0lwQeqL2rz2DB1c6NVaLinjhsUTttc6NzVeHV5QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCvrt8pxS8FQubZfSGQ4m4g8EkgRHMM84DdyGyATOoCpQG5m09Q9xDmOupcb14fnDD3ScRLRAZCkOEgC3rYi8EgzQ+9KtTBLYNY2zHGW9QKDQWyKinXs+BsUTFQI02y1qM2A+0iy9O1CW1/iYu/q36OuxE9+Lj4bZfTU1KGL7e/fsrQfI82nZ9qeix0YGItgvOwK7QPqTanLdteImv8/IQMm6jZz8wvY3dEfilFPHMnfWznU8fucEWejtPKIuL1h600hNWubtbpgKFAGCauGP1x/2252zIT2vnces5nDzTAZX9cP5UTifPyQhC4i/YkWdN9IaKU/GYouU9AHVsYMraJ</X509Certificate>
                    </X509Data>
                </KeyInfo>
            </KeyDescriptor>
            <fed:TargetScopes>
                <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                    <wsa:Address>https://sts.windows.net/56564e0f-83d3-4b52-92e8-a6bb9ea36564/</wsa:Address>
                </wsa:EndpointReference>
            </fed:TargetScopes>
            <fed:ApplicationServiceEndpoint>
                <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                    <wsa:Address>
                        https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/wsfed</wsa:Address>
                </wsa:EndpointReference>
            </fed:ApplicationServiceEndpoint>
            <fed:PassiveRequestorEndpoint>
                <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                    <wsa:Address>
                        https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/wsfed</wsa:Address>
                </wsa:EndpointReference>
            </fed:PassiveRequestorEndpoint>
        </RoleDescriptor>
        <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
            <KeyDescriptor use="signing">
                <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                    <X509Data>
                        <X509Certificate>
                            MIIC8DCCAdigAwIBAgIQHyn3TUD73aRKdHUKO4eofzANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMzA4MTYxMjAxNTFaFw0yNjA4MTYxMjAxNTBaMDQxMjAwBgNVBAMTKU1pY3Jvc29mdCBBenVyZSBGZWRlcmF0ZWQgU1NPIENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3moERWAUAXad8gE+6k+I0oqjEeB281VDzPWc4ISAqHcXsPrxKO3JTKg/EhLO+zeJTC4J9gZu0tvonYcQ8nk55t9WvkZvj6omvS30GnPZ4lMTXWxadhNCouvZbve24ntWRkbWEXpQj7wRQ2uLPSgYDxoDkT4Jujt7QEZLO8zFpBhZrX4Yi4COFcCySFkzMTzjfDRwJ94+b+OMZuI7qo2XjGfrvdY4Z75Jd96dBq92H9f8UVTHBJW4Ked9hBt1T33/goW9lekMlZ0eB78Rlq7KD+jiKJA1BqYBtyZWgE2b96Nr+By0lwQeqL2rz2DB1c6NVaLinjhsUTttc6NzVeHV5QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCvrt8pxS8FQubZfSGQ4m4g8EkgRHMM84DdyGyATOoCpQG5m09Q9xDmOupcb14fnDD3ScRLRAZCkOEgC3rYi8EgzQ+9KtTBLYNY2zHGW9QKDQWyKinXs+BsUTFQI02y1qM2A+0iy9O1CW1/iYu/q36OuxE9+Lj4bZfTU1KGL7e/fsrQfI82nZ9qeix0YGItgvOwK7QPqTanLdteImv8/IQMm6jZz8wvY3dEfilFPHMnfWznU8fucEWejtPKIuL1h600hNWubtbpgKFAGCauGP1x/2252zIT2vnces5nDzTAZX9cP5UTifPyQhC4i/YkWdN9IaKU/GYouU9AHVsYMraJ</X509Certificate>
                    </X509Data>
                </KeyInfo>
            </KeyDescriptor>
            <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                Location="https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/saml2" />
            <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                Location="https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/saml2" />
            <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                Location="https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/saml2" />
        </IDPSSODescriptor>
    </EntityDescriptor>
