apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "samlproxy.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-cm-{{.Values.customer}}-{{.Values.purpose}}-{{ include "samlproxy.fullname" . }}-idp-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
data:
  saml_idp.xml: ""
