apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{- include "samlproxy.labels" . | nindent 4 }}
  name: {{.Values.k8sPrefix}}-externalsecret-{{.Values.customer}}-{{.Values.purpose}}-{{ include "samlproxy.fullname" . }}-sp-{{.Values.stage}}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: {{.Values.k8sPrefix}}-clustersecretstore-{{.Values.customer}}-{{.Values.purpose}}-aws-secretsmanager-{{.Values.stage}}
    kind: ClusterSecretStore
  target:
    name: {{.Values.k8sPrefix}}-secret-{{.Values.customer}}-{{.Values.purpose}}-{{ include "samlproxy.fullname" . }}-sp-{{.Values.stage}}
    creationPolicy: Owner
  data:
  - secretKey: saml_sp.cert
    remoteRef:
      key: {{.Values.awsAccount}}-secret-{{.Values.customer}}-{{.Values.purpose}}-saml-sp-{{.Values.stage}}
      property: saml_sp.cert
  - secretKey: saml_sp.key
    remoteRef:
      key: {{.Values.awsAccount}}-secret-{{.Values.customer}}-{{.Values.purpose}}-saml-sp-{{.Values.stage}}
      property: saml_sp.key
  - secretKey: saml_sp.xml
    remoteRef:
      key: {{.Values.awsAccount}}-secret-{{.Values.customer}}-{{.Values.purpose}}-saml-sp-{{.Values.stage}}
      property: saml_sp.xml
