{{- if and .Values.global.networkPolicy.create .Values.global.networkPolicy.defaultDenyIngress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "argo-cd.labels" (dict "context" .) | nindent 4 }}
  name: {{.Values.k8sPrefix}}-networkpolicy-{{.Values.customer}}-{{.Values.purpose}}-{{ template "argo-cd.fullname" . }}-default-deny-{{.Values.stage}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
