apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  labels:
    {{- include "argo-cd.labels" (dict "context" .) | nindent 4 }}
    traffic-type: admin
  name: {{.Values.k8sPrefix}}-serverstransport-{{.Values.customer}}-{{.Values.purpose}}-{{ template "argo-cd.fullname" . }}-{{.Values.stage}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  insecureSkipVerify: true
